name: "🚀 Feature Request"
description: Suggest an idea for this project
title: '[Feature]: '
labels:
  - enhancement

body:
  - type: markdown
    attributes:
      value: |
        Please, provide as many information and knowledge as possible, so the feature can be correctly designed and developed.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      placeholder: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: "Describe the solution you'd like" 
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered" 
      placeholder: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false
  - type: textarea
    id: additionalcontext
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct (accessible in the root of this repository).
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
